name: Build native binaries

on:
  release:
    types:
      - prereleased

jobs:
  build-and-publish:
    name: Build library over ${{ matrix.os }} for Node v${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [16]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Configure makefile
        run: npm run configure --production
      - name: Build binaries
        run: npm run build --production
      - name: Upload binaries
        run: npm run uploadBinaries
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-and-publish-aarch64:
    name: Build library over Linux (arm64) for Node v${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build binaries
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}

          env: |
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          install: |
            apt-get update
            apt-get install awscli -yq
            aws --version

          run: |
            npm install
            npm run configure --production
            npm run build --production
            npm run uploadBinaries
